import { useEffect, useMemo, useState } from 'react'
import { Copy, MoreHorizontal, Plus, Search, Trash2, Webhook, Workflow as WorkflowIcon, Zap } from 'lucide-react'
import { Link, useNavigate, useOutletContext } from 'react-router-dom'
import { api } from '../api/client'
import ConfirmModal from '../components/ConfirmModal'
import EmptyState from '../components/EmptyState'
import type { Workflow } from '../types'

export default function WorkflowsPage(){const [rows,setRows]=useState<Workflow[]>([]);const [filter,setFilter]=useState('all');const [remove,setRemove]=useState<Workflow|null>(null);const nav=useNavigate();const ctx=useOutletContext<{search:string}>();const load=()=>api<Workflow[]>('/api/v1/workflows').then(setRows);useEffect(()=>{load()},[]);const visible=useMemo(()=>rows.filter(w=>(filter==='all'||(filter==='active'?w.active:!w.active))&&(`${w.name} ${w.description}`).toLowerCase().includes((ctx.search||'').toLowerCase())),[rows,filter,ctx.search]);const clone=async(w:Workflow)=>{await api(`/api/v1/workflows/${w.id}/clone`,{method:'POST'});load()};const del=async()=>{if(!remove)return;await api(`/api/v1/workflows/${remove.id}`,{method:'DELETE'});setRemove(null);load()};return <><div className="page-header"><div><span className="eyebrow">Build</span><h1>Workflows</h1><p>Create, manage and run your automation pipelines.</p></div><button className="btn primary" onClick={()=>nav('/workflows/new')}><Plus size={16}/>New workflow</button></div><div className="toolbar"><div className="segmented"><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>All <b>{rows.length}</b></button><button className={filter==='active'?'active':''} onClick={()=>setFilter('active')}>Active</button><button className={filter==='paused'?'active':''} onClick={()=>setFilter('paused')}>Paused</button></div><span className="toolbar-note"><Search size={14}/>Use global search to filter</span></div>{visible.length?<div className="workflow-list">{visible.map(w=><article className="workflow-list-card" key={w.id}><Link className="workflow-main" to={`/workflows/${w.id}`}><span className={`workflow-symbol ${w.trigger_type}`} >{w.trigger_type==='webhook'?<Webhook/>:w.trigger_type==='schedule'?<Zap/>:<WorkflowIcon/>}</span><div><h3>{w.name}</h3><p>{w.description||'No description yet.'}</p><div className="flow-meta"><span className={`state-dot ${w.active?'on':'off'}`}/>{w.active?'Active':'Paused'}<i/> {w.trigger_type}<i/> {w.steps.length} steps</div></div></Link><div className="workflow-actions"><button className="icon-btn" title="Clone" onClick={()=>clone(w)}><Copy size={15}/></button><button className="icon-btn danger-hover" title="Delete" onClick={()=>setRemove(w)}><Trash2 size={15}/></button><button className="icon-btn"><MoreHorizontal size={16}/></button></div></article>)}</div>:<EmptyState title="No workflows here" copy="Create your first workflow or change the current filter." action={<button className="btn primary" onClick={()=>nav('/workflows/new')}>Create workflow</button>}/>}<ConfirmModal open={!!remove} title="Delete workflow?" copy={`“${remove?.name}” and its execution history will be permanently removed.`} onCancel={()=>setRemove(null)} onConfirm={del} confirmLabel="Delete"/></>}
